---
application: "customer"
schemaVersion: "applicationDescriptor/0.11.0"
description: ""
owner: "None"
sources:
- name: "cobol"
  repositoryPath: "src/cobol"
  language: "COBOL"
  languageProcessor: "Cobol.groovy"
  fileExtension: "cbl"
  artifactsType: "Program"
  files:
  - name: "CAB1"
    type: "UNKNOWN"
    usage: "main"
  - name: "CAM1"
    type: "UNKNOWN"
    usage: "internal submodule"
  - name: "CAO1"
    type: "UNKNOWN"
    usage: "main"
- name: "copy"
  repositoryPath: "src/copy"
  language: "COBOL"
  languageProcessor: "none"
  fileExtension: "cpy"
  artifactsType: "Include File"
  files:
  - name: "CAD1REC"
    type: "UNKNOWN"
    usage: "private"
  - name: "CAD1SQL"
    type: "UNKNOWN"
    usage: "unused"
  - name: "CAM1"
    type: "UNKNOWN"
    usage: "private"
baselines:
- branch: "main"
  type: "release"
  reference: "rel-1.0.0"
  buildid: "baseline"
- branch: "release/rel-1.0.0"
  type: "release"
  reference: "rel-1.0.0"
  buildid: "baseline"
dependencies:
- name: "base"
  type: "release"
  reference: "rel-1.0.0"
  buildid: "2025-06-17_13-39-12"
